
# https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
utc_offset = -5 # can without this, then it will be 0 (UTC)

# used to specified format of datatime in csv file, this is the default one if not provided.
# for t type only
# format="%Y-%m-%d %H:%M:%S"

# support data type:
# b, B, s, S, i, I, l, L, f, d, t

[[row]] # row definition
column = "starttime" # column name in csv
type = "t" # data type to convert
alias = "timestamp" # alias for output

[[row]]
column = "start station id"
type = "S"
alias = "start_station"

[[row]]
column = "end station id"
type = "S"
alias = "end_station"

[[row]]
column = "tripduration"
type = "S"
alias = "durations"
