utc_offset = -5 # America/New_York

# used to specified format of datatime in csv file, this is the default one if not provided.
# for t type only
# format="%Y-%m-%d %H:%M:%S"

# support data type:
# b, B, s, S, i, I, l, L, f, d, t

[[row]] # row definition

alias = "timestamp" # alias for output
column = "date" # column name in csv
type = "t" # data type to convert

[[row]]

alias = "weather"
column = "weather" 
type = "B"

[[row]]

alias = "temp"
column = "temp" 
type = "f"